/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Lb.Model
{

    /// <summary>
    ///  exportTask
    /// </summary>
    public class ExportTask
    {

        ///<summary>
        /// 导出地域
        ///</summary>
        public string Region{ get; set; }
        ///<summary>
        /// 导出lb的类型：alb, nlb, dnlb
        ///</summary>
        public string LoadBalancerType{ get; set; }
        ///<summary>
        /// 导出任务的任务Id
        ///</summary>
        public string TaskId{ get; set; }
        ///<summary>
        /// 导出文件的文件名
        ///</summary>
        public string FileName{ get; set; }
        ///<summary>
        /// 导出任务的状态：2. 任务处理中; 3. 任务完成; 4. 任务失败
        ///</summary>
        public int? Status{ get; set; }
        ///<summary>
        /// 导出任务的创建时间
        ///</summary>
        public string CreatedTime{ get; set; }
        ///<summary>
        /// 导出文件的下载地址
        ///</summary>
        public string DownloadUrl{ get; set; }
    }
}
