/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 实例管理相关接口
 * API related to waf instance
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;
using JDCloudSDK.Core.Service;

using JDCloudSDK.Common.Model;
using JDCloudSDK.Core.Annotation;

namespace  JDCloudSDK.Vpcwaf.Apis
{

    /// <summary>
    /// 查询WAF实例列表
    /// </summary>
    public class DescribeWafsRequest : JdcloudRequest
    {
        ///<summary>
        ///页码；默认为1
        ///</summary>
        public   int? PageNumber{ get; set; }
        ///<summary>
        ///分页大小；默认为10；取值范围[10, 100]
        ///</summary>
        public   int? PageSize{ get; set; }
        ///<summary>
        ///查询条件,当前仅支持 ids(Waf实例id,字符串数组),albIds(绑定的LB id,字符串数组),name(WAF名称,字符串) 精确匹配过滤
        ///</summary>
        public List<Filter> Filters{ get; set; }

        ///<summary>
        ///当前仅支持根据WAF创建时间(createAt)排序
        ///</summary>
        public List<Sort> Sorts{ get; set; }

        ///<summary>
        ///地域 Id
        ///Required:true
        ///</summary>
        [Required]
        public override  string RegionId{ get; set; }
    }
}