/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Function OpenAPI
 * 
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;
using JDCloudSDK.Core.Service;

using JDCloudSDK.Core.Annotation;

namespace  JDCloudSDK.Function.Apis
{

    /// <summary>
    ///  控制台测试执行函数
    /// </summary>
    public class InvokeRequest : JdcloudRequest
    {
        ///<summary>
        /// 执行函数的输入事件
        ///Required:true
        ///</summary>
        [Required]
        public   string Event{ get; set; }
        ///<summary>
        /// Region ID
        ///Required:true
        ///</summary>
        [Required]
        public override  string RegionId{ get; set; }
        ///<summary>
        /// 函数名称
        ///Required:true
        ///</summary>
        [Required]
        public   string FunctionName{ get; set; }
        ///<summary>
        /// 版本名称
        ///Required:true
        ///</summary>
        [Required]
        public   string VersionName{ get; set; }
    }
}