/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Iotedge.Model
{

    /// <summary>
    ///  describeAppsRespVO
    /// </summary>
    public class DescribeAppsRespVO
    {

        ///<summary>
        /// App名称
        ///</summary>
        public string AppName{ get; set; }
        ///<summary>
        /// ARKID
        ///</summary>
        public string ArkId{ get; set; }
        ///<summary>
        /// APPID
        ///</summary>
        public string AppId{ get; set; }
        ///<summary>
        /// APP版本
        ///</summary>
        public string AppVersion{ get; set; }
        ///<summary>
        /// 修改时间
        ///</summary>
        public string ReleaseTime{ get; set; }
        ///<summary>
        /// APP版本
        ///</summary>
        public string AppStatus{ get; set; }
        ///<summary>
        /// 上线时间
        ///</summary>
        public string OnlineTime{ get; set; }
        ///<summary>
        /// 镜像地址
        ///</summary>
        public string AppDockerPath{ get; set; }
        ///<summary>
        /// 模板ID
        ///</summary>
        public string TmId{ get; set; }
        ///<summary>
        /// 模板名称
        ///</summary>
        public string TmName{ get; set; }
        ///<summary>
        /// APP别名
        ///</summary>
        public string AppDisplayName{ get; set; }
        ///<summary>
        /// APP运行状态
        ///</summary>
        public string RunStatus{ get; set; }
        ///<summary>
        /// APP部署状态
        ///</summary>
        public string DeployAppStatus{ get; set; }
        ///<summary>
        /// APP描述
        ///</summary>
        public string AppDesc{ get; set; }
        ///<summary>
        /// App部署产品KEY
        ///</summary>
        public string ProductKey{ get; set; }
        ///<summary>
        /// AppDeviceIdentifier
        ///</summary>
        public string Identifier{ get; set; }
    }
}
