/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Statistics
 * 数据统计分析相关接口
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;
using JDCloudSDK.Core.Service;

using JDCloudSDK.Core.Annotation;

namespace  JDCloudSDK.Vod.Apis
{

    /// <summary>
    ///  查询CDN统计数据
    /// </summary>
    public class QueryCDNStatsDataRequest : JdcloudRequest
    {
        ///<summary>
        /// 起始时间
        ///Required:true
        ///</summary>
        [Required]
        public   string StartTime{ get; set; }
        ///<summary>
        /// 结束时间
        ///Required:true
        ///</summary>
        [Required]
        public   string EndTime{ get; set; }
        ///<summary>
        /// 域名
        ///</summary>
        public   string DomainNames{ get; set; }
        ///<summary>
        /// 运营商
        ///</summary>
        public   string Isp{ get; set; }
        ///<summary>
        /// 地域
        ///</summary>
        public   string Area{ get; set; }
        ///<summary>
        /// 待查询字段。可多选，多选时以逗号分隔。可选字段：| avgbandwidth - 平均带宽 pv - 请求次数 hitpv - 命中次数 flow - 流量 codestat - 状态码统计，记录每种状态码的次数，Hash结构，如 {&quot;200&quot;:10, &quot;404&quot;:1} uv - 请求人数
        ///Required:true
        ///</summary>
        [Required]
        public   string Fields{ get; set; }
        ///<summary>
        /// 时间周期，即时间粒度
        ///</summary>
        public   string Period{ get; set; }
    }
}