/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Dbaudit.Model
{

    /// <summary>
    ///  数据库审计agent信息
    /// </summary>
    public class AgentInfo
    {

        ///<summary>
        /// agentID
        ///</summary>
        public string AgnetId{ get; set; }
        ///<summary>
        /// 主机ID
        ///</summary>
        public string HostId{ get; set; }
        ///<summary>
        /// 操作系统类型 Windows Server | CentOS
        ///</summary>
        public string OsType{ get; set; }
        ///<summary>
        /// 主机名称
        ///</summary>
        public string HostName{ get; set; }
        ///<summary>
        /// agent运行状态 0 安装中 1 运行中 2 离线 3 已卸载 4 待配置 5 安装失败(ifrit安装失败，需要重试或者手动安装)
        ///</summary>
        public int? AgentStatus{ get; set; }
        ///<summary>
        /// ifrit客户端的状态 0 安装成功 1 离线状态
        ///</summary>
        public int? IfritStatus{ get; set; }
        ///<summary>
        /// agent审计的数据库数量
        ///</summary>
        public int? AuditCount{ get; set; }
        ///<summary>
        /// 是否限制CPU/MEM
        /// 0 否 
        /// 1 是 此时cpuLimit/memLimit为必填项
        /// 
        ///</summary>
        public int? LimitStatus{ get; set; }
        ///<summary>
        /// CPU限制，单位%
        ///</summary>
        public float? CpuLimit{ get; set; }
        ///<summary>
        /// 内存限制，单位%
        ///</summary>
        public float? MemLimit{ get; set; }
        ///<summary>
        /// CPU实时占比，单位%
        ///</summary>
        public float? CpuPercent{ get; set; }
        ///<summary>
        /// 内存实时占比，单位%
        ///</summary>
        public float? MemPercert{ get; set; }
        ///<summary>
        /// 内存总量,单位MB
        ///</summary>
        public int? MemTotal{ get; set; }
        ///<summary>
        /// CPU核数,单位核数
        ///</summary>
        public int? CpuTotal{ get; set; }
        ///<summary>
        /// agent安装时间
        ///</summary>
        public string InstallTime{ get; set; }
        ///<summary>
        /// 最后一次上报数据时间
        ///</summary>
        public string LastUpdateTime{ get; set; }
    }
}
