/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Cdn.Model
{

    /// <summary>
    ///  attackLogRecord
    /// </summary>
    public class AttackLogRecord
    {

        ///<summary>
        /// 攻击峰值
        ///</summary>
        public float? AttackTraffic{ get; set; }
        ///<summary>
        /// 攻击类型
        ///</summary>
        public List<string> AttackType{ get; set; }
        ///<summary>
        /// 黑洞封禁 0-&gt;未封禁 1-&gt;封禁
        ///</summary>
        public int? BlackHole{ get; set; }
        ///<summary>
        /// 攻击结束时间 utc时间
        ///</summary>
        public string EndTime{ get; set; }
        ///<summary>
        /// 用户pin
        ///</summary>
        public string Pin{ get; set; }
        ///<summary>
        /// 攻击开始时间 utc时间
        ///</summary>
        public string StartTime{ get; set; }
        ///<summary>
        /// 攻击峰值单位 流量单位
        ///</summary>
        public string Unit{ get; set; }
    }
}
