/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;

using JDCloudSDK.Core.Annotation;

namespace JDCloudSDK.Cdn.Model
{

    /// <summary>
    /// cdnCache
    /// </summary>
    public class CdnCache
    {

        ///<summary>
        ///缓存方式：0表示不缓存，1表示自定义。 默认是自定义缓存
        ///Required:true
        ///</summary>
        [Required]
        public string CacheType{ get; set; }
        ///<summary>
        ///权重
        ///Required:true
        ///</summary>
        [Required]
        public string Weight{ get; set; }
        ///<summary>
        ///缓存策略内容
        ///Required:true
        ///</summary>
        [Required]
        public string Content{ get; set; }
        ///<summary>
        ///过期时间，时间秒
        ///Required:true
        ///</summary>
        [Required]
        public int Ttl{ get; set; }
        ///<summary>
        ///add,update,delete 其中update和delete必须要configid,缓存配置id
        ///Required:true
        ///</summary>
        [Required]
        public string Status{ get; set; }
        ///<summary>
        ///缓存配置id
        ///</summary>
        public string ConfigId{ get; set; }
    }
}
