/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Cdn.Model
{

    /// <summary>
    /// cdnRefreshQuery
    /// </summary>
    public class CdnRefreshQuery
    {

        ///<summary>
        ///任务id
        ///</summary>
        public string Taskid{ get; set; }
        ///<summary>
        ///结果状态 0，刷新成功，1正在进行中，2刷新失败
        ///</summary>
        public string Status{ get; set; }
        ///<summary>
        ///提示信息
        ///</summary>
        public string Msg{ get; set; }
    }
}
