/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Dms.Model
{

    /// <summary>
    ///  stardbSplitInfo
    /// </summary>
    public class StardbSplitInfo
    {

        ///<summary>
        /// 切分方式，&quot;MODULO：取模, &quot;HASH&quot;：哈希, &quot;DB_TABLE&quot;：分库分表, &quot;YYYYMMDD&quot;,&quot;YYYYMM&quot;,&quot;MM&quot;,&quot;MMDD&quot;
        ///</summary>
        public string SplitType{ get; set; }
        ///<summary>
        /// 切分表数量,表切分方式为哈希取模时必需
        ///</summary>
        public int? TableSplitCount{ get; set; }
        ///<summary>
        /// 切分列名称，第一项为切分表的列（必需），第二项为切分库的列（非必需)
        ///</summary>
        public List<string> ColumnNames{ get; set; }
        ///<summary>
        /// 起始时间，切分方式为时间时必需，格式为20220125
        ///</summary>
        public string SplitDateBegin{ get; set; }
        ///<summary>
        /// 结束时间，切分方式为时间时必需，格式为20220125
        ///</summary>
        public string SplitDateEnd{ get; set; }
    }
}
