/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Starshield.Model
{

    /// <summary>
    ///  wAFRulePackage
    /// </summary>
    public class WAFRulePackage
    {

        ///<summary>
        /// WAF包标识符标签
        ///</summary>
        public string Id{ get; set; }
        ///<summary>
        /// 防火墙包的名称
        ///</summary>
        public string Name{ get; set; }
        ///<summary>
        /// 防火墙包的目的/功能摘要
        ///</summary>
        public string Description{ get; set; }
        ///<summary>
        /// Detection_mode
        ///</summary>
        public string Detection_mode{ get; set; }
        ///<summary>
        /// 区标识符标签
        ///</summary>
        public string Zone_id{ get; set; }
        ///<summary>
        /// 指示对域应用防火墙包。
        ///</summary>
        public string Status{ get; set; }
        ///<summary>
        /// 防火墙包的敏感度。
        ///</summary>
        public string Sensitivity{ get; set; }
        ///<summary>
        /// 将对防火墙包下的规则执行的默认操作。
        ///</summary>
        public string Action_mode{ get; set; }
    }
}
