/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Sts.Model
{

    /// <summary>
    ///  credentials
    /// </summary>
    public class Credentials
    {

        ///<summary>
        /// 临时accessKey
        ///</summary>
        public string AccessKey{ get; set; }
        ///<summary>
        /// 临时secretKey
        ///</summary>
        public string SecretKey{ get; set; }
        ///<summary>
        /// 临时安全令牌
        ///</summary>
        public string SessionToken{ get; set; }
        ///<summary>
        /// 有效期
        ///</summary>
        public string Expiration{ get; set; }
    }
}
