/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * NameSpace相关 API
 * 流数据总线NameSpace相关信息接口
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;
using JDCloudSDK.Core.Service;

using JDCloudSDK.Streamcomputer.Model;

namespace  JDCloudSDK.Streamcomputer.Apis
{

    /// <summary>
    ///  创建或者更新storage
    /// </summary>
    public class GetStorageListResult : JdcloudResult
    {
        ///<summary>
        /// StorageList
        ///</summary>
        public List<Storage> StorageList{ get; set; }

    }
}