/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Alarm Template APIs
 * monitor API
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;
using JDCloudSDK.Core.Service;

using JDCloudSDK.Core.Annotation;
using JDCloudSDK.Monitor.Model;

namespace  JDCloudSDK.Monitor.Apis
{

    /// <summary>
    ///  应用报警模板到资源
    /// </summary>
    public class ApplyTemplateRequest : JdcloudRequest
    {
        ///<summary>
        /// 幂等性校验参数,最长36位
        ///Required:true
        ///</summary>
        [Required]
        public   string ClientToken{ get; set; }
        ///<summary>
        /// 联系人列表
        ///</summary>
        public List<BaseContact> Contacts{ get; set; }

        ///<summary>
        /// dataCenters，该资源所处地域，与resourceIds一一对应
        ///</summary>
        public List<string> DataCenters{ get; set; }

        ///<summary>
        /// 资源ID列表，resourceIds数量为1--40，每一项不能为空或包含*
        ///</summary>
        public List<string> ResourceIds{ get; set; }

        ///<summary>
        /// 资源类型
        ///Required:true
        ///</summary>
        [Required]
        public   string ServiceCode{ get; set; }
        ///<summary>
        /// 标签组，模板下面规则对应的tags，与resourceIds一一对应
        ///</summary>
        public List<Dictionary<string,string>> TagsArray{ get; set; }

        ///<summary>
        /// 模板类型，1表示默认模板，2表示用户自定义模板
        ///Required:true
        ///</summary>
        [Required]
        public   long TemplateType{ get; set; }
        ///<summary>
        /// 回调content 注:仅webHookUrl和webHookContent均不为空时,才会创建webHook
        ///</summary>
        public   string WebHookContent{ get; set; }
        ///<summary>
        /// webHook协议,https或http 注:此处需和webHookUrl相匹配
        ///</summary>
        public   string WebHookProtocol{ get; set; }
        ///<summary>
        /// 回调secret,用户请求签名,防伪造
        ///</summary>
        public   string WebHookSecret{ get; set; }
        ///<summary>
        /// 回调url
        ///</summary>
        public   string WebHookUrl{ get; set; }
        ///<summary>
        /// 模板 id
        ///Required:true
        ///</summary>
        [Required]
        public   string TemplateId{ get; set; }
    }
}