/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.User.Model
{

    /// <summary>
    ///  transReqVo
    /// </summary>
    public class TransReqVo
    {

        ///<summary>
        /// 离职人erp
        ///</summary>
        public string SourceErp{ get; set; }
        ///<summary>
        /// 接收人erp
        ///</summary>
        public string TargetErp{ get; set; }
        ///<summary>
        /// 交接项id
        ///</summary>
        public string ItemId{ get; set; }
        ///<summary>
        /// 交接项名称，如果交接项ID为空则交接项名称必须确保唯⼀
        ///</summary>
        public string ItemName{ get; set; }
        ///<summary>
        /// 时间戳，请求时间与系统时间不得超过10分钟，否则返回403
        ///</summary>
        public string Timestamp{ get; set; }
        ///<summary>
        /// 鉴权签名，md5加密（32位小写）
        ///</summary>
        public string Signature{ get; set; }
    }
}
