/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Elite.Model
{

    /// <summary>
    ///  jdxProductSkuVo
    /// </summary>
    public class JdxProductSkuVo
    {

        ///<summary>
        /// sku ID
        ///</summary>
        public int? SkuId{ get; set; }
        ///<summary>
        /// sku名称
        ///</summary>
        public string SkuName{ get; set; }
        ///<summary>
        /// 销售属性json字符串,version表示版本(套次、周期、套餐包类商品均有该属性),validity表示周期(周期和套餐包类商品有该属性),packageNum表示条数(只有套餐包类商品有该属性)：例如[{&quot;attrCode&quot;:&quot;version&quot;,&quot;attrValue&quot;:&quot;升级版&quot;},{&quot;attrCode&quot;:&quot;validity&quot;,&quot;attrValue&quot;:365},{&quot;attrCode&quot;:&quot;packageNum&quot;,&quot;attrValue&quot;:1000}]
        ///</summary>
        public string SaleAttributes{ get; set; }
        ///<summary>
        /// 最大购买数量
        ///</summary>
        public int? MaxBuyNum{ get; set; }
        ///<summary>
        /// 最小购买数量
        ///</summary>
        public int? MinBuyNum{ get; set; }
        ///<summary>
        /// sku 售价
        ///</summary>
        public double? SkuSellingPrice{ get; set; }
        ///<summary>
        /// 额外计费项信息
        ///</summary>
        public List<JdxSkuExtraChargeVo> SkuExtraChargeList{ get; set; }
    }
}
