/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Elite.Model
{

    /// <summary>
    ///  jdxProductVo
    /// </summary>
    public class JdxProductVo
    {

        ///<summary>
        /// 产品ID
        ///</summary>
        public int? ProductId{ get; set; }
        ///<summary>
        /// 商品名称
        ///</summary>
        public string ProductName{ get; set; }
        ///<summary>
        /// 商标图片地址
        ///</summary>
        public string TrademarkUrl{ get; set; }
        ///<summary>
        /// 所属一级分类名称
        ///</summary>
        public string CategoryLevel1Name{ get; set; }
        ///<summary>
        /// 所属二级分类名称
        ///</summary>
        public string CategoryLevel2Name{ get; set; }
        ///<summary>
        /// 交付形态
        ///</summary>
        public int? DeliveryForm{ get; set; }
        ///<summary>
        /// 交付形态名称
        ///</summary>
        public string DeliveryFormName{ get; set; }
        ///<summary>
        /// 商品简介
        ///</summary>
        public string Introduction{ get; set; }
        ///<summary>
        /// 商品定价模式 1:按套次、2:按周期、3:按套餐包
        ///</summary>
        public int? SellType{ get; set; }
        ///<summary>
        /// 商品定价模式名称
        ///</summary>
        public string SellTypeName{ get; set; }
        ///<summary>
        /// -1:不允许退款， 单位：天， 默认-1
        ///</summary>
        public int? RefundDays{ get; set; }
        ///<summary>
        /// pc端商品详情
        ///</summary>
        public string PcProductDetail{ get; set; }
        ///<summary>
        /// m端商品详情
        ///</summary>
        public string MProductDetail{ get; set; }
        ///<summary>
        /// sku详情信息
        ///</summary>
        public List<JdxProductSkuVo> ProductSkuList{ get; set; }
    }
}
