/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;

using JDCloudSDK.Core.Annotation;
using JDCloudSDK.Elite.Model;

namespace JDCloudSDK.Elite.Model
{

    /// <summary>
    ///  queryPriceParam
    /// </summary>
    public class QueryPriceParam
    {

        ///<summary>
        /// 操作类型 1:创建 2:续费 3:升降配
        ///Required:true
        ///</summary>
        [Required]
        public int Cmd{ get; set; }
        ///<summary>
        /// 打包购买包数
        ///Required:true
        ///</summary>
        [Required]
        public int PackageCount{ get; set; }
        ///<summary>
        /// OrderList
        ///Required:true
        ///</summary>
        [Required]
        public List<OrderPriceProtocolVo> OrderList{ get; set; }
    }
}
