/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * JDCLOUD BILLING Services API
 * 用户中心消费管理查询API接口
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;
using JDCloudSDK.Core.Service;

using JDCloudSDK.Core.Annotation;

namespace  JDCloudSDK.Billing.Apis
{

    /// <summary>
    ///  查询消费统计信息
    /// </summary>
    public class AdminQueryBillStatisticsInfoRequest : JdcloudRequest
    {
        ///<summary>
        /// 查询类别   1：资源账单   2：消费记录
        ///</summary>
        public   int? QueryType{ get; set; }
        ///<summary>
        /// 用户pin
        ///</summary>
        public   string Pin{ get; set; }
        ///<summary>
        /// 应用码
        ///</summary>
        public   string AppCode{ get; set; }
        ///<summary>
        /// 服务码
        ///</summary>
        public   string ServiceCode{ get; set; }
        ///<summary>
        /// 付费类型
        ///</summary>
        public   int? BillingType{ get; set; }
        ///<summary>
        /// 付费类型
        ///</summary>
        public   int? PayType{ get; set; }
        ///<summary>
        /// 付费状态
        ///</summary>
        public   int? PayState{ get; set; }
        ///<summary>
        /// 1: 按账期 2：按消费时间
        ///</summary>
        public   int? TimeType{ get; set; }
        ///<summary>
        /// 开始时间
        ///</summary>
        public   string StartTime{ get; set; }
        ///<summary>
        /// 结束时间
        ///</summary>
        public   string EndTime{ get; set; }
        ///<summary>
        /// IgnoreZero
        ///</summary>
        public   int? IgnoreZero{ get; set; }
        ///<summary>
        /// 资源ID
        ///</summary>
        public   string ResourceId{ get; set; }
        ///<summary>
        /// 站点
        ///</summary>
        public   int? Site{ get; set; }
        ///<summary>
        /// 角色
        ///</summary>
        public   int? Role{ get; set; }
        ///<summary>
        /// 区域
        ///</summary>
        public   string Region{ get; set; }
        ///<summary>
        /// RegionId
        ///Required:true
        ///</summary>
        [Required]
        public override  string RegionId{ get; set; }
    }
}