/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 云主机
 * 与主机操作相关的接口
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using JDCloudSDK.Core.Client;
using JDCloudSDK.Core.Http;
using System;
using System.Collections.Generic;
using System.Text;

namespace JDCloudSDK.Vm.Client
{

    /// <summary>
    ///  
        /// 修改一台云主机中的云硬盘属性。
        /// 
        /// 详细操作说明请参考帮助文档：[配置云硬盘删除属性](https://docs.jdcloud.com/cn/virtual-machines/configurate-delete-attributes)
        /// 
        /// ## 接口说明
        /// - 该接口当前只能修改实例中的云硬盘随实例删除属性。
        /// - 仅按配置计费、并且非共享型的云硬盘支持修改。
        /// - 包年包月计费的云硬盘该属性不生效，实例删除时云硬盘将保留。
        /// 
    /// </summary>
    public class ModifyInstanceDiskAttributeExecutor : JdcloudExecutor
    {
        /// <summary>
        ///  
        /// 修改一台云主机中的云硬盘属性。
        /// 
        /// 详细操作说明请参考帮助文档：[配置云硬盘删除属性](https://docs.jdcloud.com/cn/virtual-machines/configurate-delete-attributes)
        /// 
        /// ## 接口说明
        /// - 该接口当前只能修改实例中的云硬盘随实例删除属性。
        /// - 仅按配置计费、并且非共享型的云硬盘支持修改。
        /// - 包年包月计费的云硬盘该属性不生效，实例删除时云硬盘将保留。
        /// 接口的Http 请求方法
        /// </summary>
        public override  string Method
        {
            get {
                return "POST";
            }
        }
        /// <summary>
        ///  
        /// 修改一台云主机中的云硬盘属性。
        /// 
        /// 详细操作说明请参考帮助文档：[配置云硬盘删除属性](https://docs.jdcloud.com/cn/virtual-machines/configurate-delete-attributes)
        /// 
        /// ## 接口说明
        /// - 该接口当前只能修改实例中的云硬盘随实例删除属性。
        /// - 仅按配置计费、并且非共享型的云硬盘支持修改。
        /// - 包年包月计费的云硬盘该属性不生效，实例删除时云硬盘将保留。
        /// 接口的Http资源请求路径
        /// </summary>
        public override string Url
        {
            get {
            return "/regions/{regionId}/instances/{instanceId}:modifyInstanceDiskAttribute";
            }
        }
    }
}
