/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 用户管理接口
 * 用户管理接口
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;
using JDCloudSDK.Core.Service;


namespace  JDCloudSDK.Iam.Apis
{

    /// <summary>
    /// 根据用户pin获取用户基础信息
    /// </summary>
    public class DescribeBaseInfoResult : JdcloudResult
    {
        ///<summary>
        ///用户pin
        ///</summary>
        public   string Pin{ get; set; }
        ///<summary>
        ///用户是否可用，true表示可用，false表示不可用，该用户在黑名单中
        ///</summary>
        public   bool Enabled{ get; set; }
        ///<summary>
        ///用户类型 1：个人，2：企业 ,3：个人升级企业
        ///</summary>
        public   int? UserType{ get; set; }
        ///<summary>
        ///-1-未认证（个人），1-已认证（个人）
        ///</summary>
        public   int? PersonAuthStatus{ get; set; }
        ///<summary>
        ///0-审核中（企业），1-已认证（企业），2-未通过（企业）
        ///</summary>
        public   int? CompanyaAuthStatus{ get; set; }
        ///<summary>
        ///用户唯一id
        ///</summary>
        public   string AccountId{ get; set; }
        ///<summary>
        ///用户的扩展信息
        ///</summary>
        public   string Meta{ get; set; }
    }
}