/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 安全令牌管理接口
 * 安全令牌管理接口
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;
using JDCloudSDK.Core.Service;


namespace  JDCloudSDK.Iam.Apis
{

    /// <summary>
    /// 获取操作保护设置信息
    /// </summary>
    public class GetSensitiveOpSettingResult : JdcloudResult
    {
        ///<summary>
        ///操作保护启用状态：0-未启用, 1-已启用
        ///</summary>
        public   int? Status{ get; set; }
        ///<summary>
        ///操作保护验证方式：0-无, 1-短信, 2-邮箱, 3-MFA
        ///</summary>
        public   int? Type{ get; set; }
    }
}