/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Clouddnsservice.Model
{

    /// <summary>
    /// viewTree
    /// </summary>
    public class ViewTree
    {

        ///<summary>
        ///此解析线路是否禁用
        ///</summary>
        public bool Disabled{ get; set; }
        ///<summary>
        ///解析线路的名称
        ///</summary>
        public string Label{ get; set; }
        ///<summary>
        ///此数据是否是叶子节点
        ///</summary>
        public bool Leaf{ get; set; }
        ///<summary>
        ///解析线路ID
        ///</summary>
        public int? Value{ get; set; }
        ///<summary>
        ///Children
        ///</summary>
        public List<ViewTree> Children{ get; set; }
    }
}
