/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Media Category
 * 分类管理
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Vod.Model
{

    /// <summary>
    ///  规则配置对象
    /// </summary>
    public class Config
    {

        ///<summary>
        /// 启用策略：拒绝-denial | 允许-allowance
        ///</summary>
        public string Strategy{ get; set; }
        ///<summary>
        /// Referer域名列表
        ///</summary>
        public List<string> Domains{ get; set; }
        ///<summary>
        /// 允许 referer 为空，如允许浏览器直接访问等
        ///</summary>
        public bool AllowBlank{ get; set; }
    }
}
