/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Vod.Model
{

    /// <summary>
    ///  剪裁操作参数
    /// </summary>
    public class CropParams
    {

        ///<summary>
        /// 剪裁图像横坐标
        ///</summary>
        public int? X{ get; set; }
        ///<summary>
        /// 剪裁图像纵坐标
        ///</summary>
        public int? Y{ get; set; }
        ///<summary>
        /// 剪裁图像宽度
        ///</summary>
        public int? Width{ get; set; }
        ///<summary>
        /// 剪裁图像高度
        ///</summary>
        public int? Height{ get; set; }
    }
}
