/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * NodeGroup
 * 节点组相关接口
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;
using JDCloudSDK.Core.Service;

using JDCloudSDK.Core.Annotation;
using JDCloudSDK.Kubernetes.Model;

namespace  JDCloudSDK.Kubernetes.Apis
{

    /// <summary>
    ///  创建k8s的nodeGroup
        ///         /// 要求集群状态为running
        ///         /// 
    /// </summary>
    public class CreateNodeGroupRequest : JdcloudRequest
    {
        ///<summary>
        /// 名称（同一用户的 cluster 内部唯一）
        ///Required:true
        ///</summary>
        [Required]
        public   string Name{ get; set; }
        ///<summary>
        /// 描述
        ///</summary>
        public   string Description{ get; set; }
        ///<summary>
        /// node group所属的cluster
        ///Required:true
        ///</summary>
        [Required]
        public   string ClusterId{ get; set; }
        ///<summary>
        /// 节点组配置
        ///Required:true
        ///</summary>
        [Required]
        public   NodeConfigSpec NodeConfig{ get; set; }
        ///<summary>
        /// nodeGroup初始化大小
        ///Required:true
        ///</summary>
        [Required]
        public   int InitialNodeCount{ get; set; }
        ///<summary>
        /// k8s运行的vpc
        ///Required:true
        ///</summary>
        [Required]
        public   string VpcId{ get; set; }
        ///<summary>
        /// k8s的node的cidr
        ///Required:true
        ///</summary>
        [Required]
        public   string NodeCidr{ get; set; }
        ///<summary>
        /// 是否开启 node group 的自动修复，默认关闭
        ///</summary>
        public   bool AutoRepair{ get; set; }
        ///<summary>
        /// 地域 ID
        ///Required:true
        ///</summary>
        [Required]
        public override  string RegionId{ get; set; }
    }
}