/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Sms.Model
{

    /// <summary>
    ///  statusReportResp
    /// </summary>
    public class StatusReportResp
    {

        ///<summary>
        /// 手机号
        ///</summary>
        public string PhoneNum{ get; set; }
        ///<summary>
        /// 发送短信的序列号
        ///</summary>
        public string SequenceNumber{ get; set; }
        ///<summary>
        /// 短信发送时间（yyyy-MM-dd HH:mm:ss)
        ///</summary>
        public string SendTime{ get; set; }
        ///<summary>
        /// 接收到回执的时间（yyyy-MM-dd HH:mm:ss)
        ///</summary>
        public string ReportTime{ get; set; }
        ///<summary>
        /// 发送状态
        ///</summary>
        public int? Status{ get; set; }
        ///<summary>
        /// 错误码
        ///</summary>
        public string Code{ get; set; }
        ///<summary>
        /// 长短信拆分序号（短短信直接返回1)
        ///</summary>
        public int? SplitNum{ get; set; }
    }
}
