/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Openjrtc.Model
{

    /// <summary>
    ///  notifyConfigObj
    /// </summary>
    public class NotifyConfigObj
    {

        ///<summary>
        /// 主键-新增时不传，更新时要传
        ///</summary>
        public long? ConfigId{ get; set; }
        ///<summary>
        /// 回调类型 1-房间回调 2-媒体回调
        ///</summary>
        public int? NotifyType{ get; set; }
        ///<summary>
        /// 回调地址
        ///</summary>
        public string Url{ get; set; }
    }
}
