/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Sessions
 * 会话统计、实时会话、事务锁、非事务锁、未提交事务等接口
 *
 * OpenAPI spec version: v2
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;
using JDCloudSDK.Core.Service;

using JDCloudSDK.Smartdba.Model;

namespace  JDCloudSDK.Smartdba.Apis
{

    /// <summary>
    ///  获取当前实例的会话信息
    /// </summary>
    public class DescribeSessionsResult : JdcloudResult
    {
        ///<summary>
        /// 实例已运行时间，单位:s
        ///</summary>
        public   int? UpTime{ get; set; }
        ///<summary>
        /// 运行中会话总数
        ///</summary>
        public   int? ActiveSession{ get; set; }
        ///<summary>
        /// 运行中会话最长时间
        ///</summary>
        public   int? MaxActiveTime{ get; set; }
        ///<summary>
        /// 存在事务等待的会话
        ///</summary>
        public   int? WaitSession{ get; set; }
        ///<summary>
        /// 会话总数
        ///</summary>
        public   int? TotalSession{ get; set; }
        ///<summary>
        /// DMS（系统）会话总数
        ///</summary>
        public   int? SystemsSession{ get; set; }
        ///<summary>
        /// 总数
        ///</summary>
        public   int? TotalCount{ get; set; }
        ///<summary>
        /// 实时会话列表
        ///</summary>
        public List<Session> Sessions{ get; set; }

        ///<summary>
        /// 按用户统计
        ///</summary>
        public List<UserStatistic> UserStatistics{ get; set; }

        ///<summary>
        /// 按访问来源统计
        ///</summary>
        public List<HostStatistic> HostStatistics{ get; set; }

        ///<summary>
        /// 按数据库统计
        ///</summary>
        public List<DBStatistic> DbStatistics{ get; set; }

    }
}