/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Jdfusion.Model
{

    /// <summary>
    ///  deploymentResourcesInfo
    /// </summary>
    public class DeploymentResourcesInfo
    {

        ///<summary>
        /// Vms
        ///</summary>
        public Dictionary<string,CreateVm> Vms{ get; set; }
        ///<summary>
        /// Eips
        ///</summary>
        public Dictionary<string,AllocateEipAddress> Eips{ get; set; }
        ///<summary>
        /// Subnets
        ///</summary>
        public Dictionary<string,CreateSubnet> Subnets{ get; set; }
        ///<summary>
        /// NetworkInterfaces
        ///</summary>
        public Dictionary<string,CreateNetInterface> NetworkInterfaces{ get; set; }
        ///<summary>
        /// Slbs
        ///</summary>
        public Dictionary<string,SlbInfo> Slbs{ get; set; }
        ///<summary>
        /// SecurityGroups
        ///</summary>
        public Dictionary<string,CreateSecurityGroup> SecurityGroups{ get; set; }
        ///<summary>
        /// SecurityGroupRules
        ///</summary>
        public Dictionary<string,CreateSgRule> SecurityGroupRules{ get; set; }
        ///<summary>
        /// Keypairs
        ///</summary>
        public Dictionary<string,CreateKeypair> Keypairs{ get; set; }
        ///<summary>
        /// Disks
        ///</summary>
        public Dictionary<string,CreateDataDisk> Disks{ get; set; }
        ///<summary>
        /// Vpcs
        ///</summary>
        public Dictionary<string,VpcInfo> Vpcs{ get; set; }
        ///<summary>
        /// VserverGroups
        ///</summary>
        public Dictionary<string,CreateVserverGroup> VserverGroups{ get; set; }
        ///<summary>
        /// HttpListeners
        ///</summary>
        public Dictionary<string,CreateLoadBalancerHTTPListener> HttpListeners{ get; set; }
        ///<summary>
        /// DiskAttachment
        ///</summary>
        public Dictionary<string,DeploymentAttachDisk> DiskAttachment{ get; set; }
        ///<summary>
        /// NetInterfaceAttachment
        ///</summary>
        public Dictionary<string,DeploymentAttachNetInterface> NetInterfaceAttachment{ get; set; }
        ///<summary>
        /// EipAssociate
        ///</summary>
        public Dictionary<string,DeploymentAssociateEip> EipAssociate{ get; set; }
        ///<summary>
        /// Rds
        ///</summary>
        public Dictionary<string,CreateRDSInstance> Rds{ get; set; }
        ///<summary>
        /// RdsDatabase
        ///</summary>
        public Dictionary<string,DeploymentRdsDatabase> RdsDatabase{ get; set; }
        ///<summary>
        /// RdsAccount
        ///</summary>
        public Dictionary<string,DeploymentRdsAccount> RdsAccount{ get; set; }
        ///<summary>
        /// RdsAccountGrant
        ///</summary>
        public Dictionary<string,DeploymentAccountGrant> RdsAccountGrant{ get; set; }
        ///<summary>
        /// Bucket
        ///</summary>
        public Dictionary<string,DeploymentBucket> Bucket{ get; set; }
        ///<summary>
        /// Variables
        ///</summary>
        public Dictionary<string,string> Variables{ get; set; }
    }
}
