/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Ucapi.Model
{

    /// <summary>
    /// vatQualification
    /// </summary>
    public class VatQualification
    {

        ///<summary>
        ///用户pin
        ///</summary>
        public string MemberName{ get; set; }
        ///<summary>
        ///纳税人识别码
        ///</summary>
        public string TaxId{ get; set; }
        ///<summary>
        ///单位名称
        ///</summary>
        public string Company{ get; set; }
        ///<summary>
        ///注册电话
        ///</summary>
        public string Phone{ get; set; }
        ///<summary>
        ///开户银行
        ///</summary>
        public string Bank{ get; set; }
        ///<summary>
        ///银行账户
        ///</summary>
        public string Account{ get; set; }
        ///<summary>
        ///注册地址
        ///</summary>
        public string Address{ get; set; }
    }
}
