/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Dcap.Model
{

    /// <summary>
    ///  instanceDesc
    /// </summary>
    public class InstanceDesc
    {

        ///<summary>
        /// 实例ID
        ///</summary>
        public string InstanceId{ get; set; }
        ///<summary>
        /// 实例名称
        ///</summary>
        public string InstanceName{ get; set; }
        ///<summary>
        /// 实例类型-规格 1-&gt;网关版本, 2-&gt;插件版本
        ///</summary>
        public int? InstanceType{ get; set; }
        ///<summary>
        /// 区域
        ///</summary>
        public string InsRegion{ get; set; }
        ///<summary>
        /// 可用区
        ///</summary>
        public string InsZone{ get; set; }
        ///<summary>
        /// 是否为透传模式
        ///</summary>
        public bool IsBypass{ get; set; }
        ///<summary>
        /// 实例运行状态: 1-&gt;创建中, 2-&gt;运行中, 3-&gt;欠费停服
        ///</summary>
        public int? Status{ get; set; }
        ///<summary>
        /// 保护的数据源ID
        ///</summary>
        public string DataSourceId{ get; set; }
        ///<summary>
        /// 创建时间
        ///</summary>
        public string CreateTime{ get; set; }
        ///<summary>
        /// 更新时间
        ///</summary>
        public string UpdateTime{ get; set; }
        ///<summary>
        /// 域名（网关版本）
        ///</summary>
        public string Domain{ get; set; }
        ///<summary>
        /// AccessKey
        ///</summary>
        public string AccessKey{ get; set; }
        ///<summary>
        /// SecretKey
        ///</summary>
        public string SecretKey{ get; set; }
    }
}
