/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 域名操作类接口
 * Openapi For JCLOUD cdn
 *
 * OpenAPI spec version: v1
 * Contact: pid-cdn@jd.com
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;
using JDCloudSDK.Core.Service;

using JDCloudSDK.Cdn.Model;

namespace  JDCloudSDK.Cdn.Apis
{

    /// <summary>
    ///  通过标签查询加速域名接口
    /// </summary>
    public class GetDomainListByFilterResult : JdcloudResult
    {
        ///<summary>
        /// TotalCount
        ///</summary>
        public   int? TotalCount{ get; set; }
        ///<summary>
        /// PageSize
        ///</summary>
        public   int? PageSize{ get; set; }
        ///<summary>
        /// PageNumber
        ///</summary>
        public   int? PageNumber{ get; set; }
        ///<summary>
        /// Domains
        ///</summary>
        public List<ListDomainItemByFilter> Domains{ get; set; }

    }
}