/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Pcdn刷新预热接口
 * Openapi For JCLOUD cdn
 *
 * OpenAPI spec version: v1
 * Contact: pid-cdn@jd.com
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;
using JDCloudSDK.Core.Service;


namespace  JDCloudSDK.Cdn.Apis
{

    /// <summary>
    ///  查询预热任务接口
    /// </summary>
    public class QueryPrefetchTaskRequest : JdcloudRequest
    {
        ///<summary>
        /// url
        ///</summary>
        public   string Url{ get; set; }
        ///<summary>
        /// 地区[huabei huadong dongbei huazhong huanan xinan xibei gangaotai]中的一个
        ///</summary>
        public   string Region{ get; set; }
        ///<summary>
        /// 运营商[ct uni cm]中的一个,分别代表电信 联通 移动
        ///</summary>
        public   string Isp{ get; set; }
        ///<summary>
        /// 查询状态 1:active维护预热中，2:表示purge中暂时停止预热
        ///</summary>
        public   int? Status{ get; set; }
        ///<summary>
        /// 同url，系统内部url对应id（url和file_id同时存在时以url为准）
        ///</summary>
        public   string FileId{ get; set; }
        ///<summary>
        /// 页码数,最小为1
        ///</summary>
        public   int? PageNumber{ get; set; }
        ///<summary>
        /// 每页大小,默认10
        ///</summary>
        public   int? PageSize{ get; set; }
        ///<summary>
        /// 1:代表控制台下发的预热任务2:代表热度计算下发的预热任务3:代表控制台、热度计算共同下发的任务
        ///</summary>
        public   int? TaskType{ get; set; }
        ///<summary>
        /// 域名
        ///</summary>
        public   string Domain{ get; set; }
    }
}