/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;

using JDCloudSDK.Core.Annotation;

namespace JDCloudSDK.Iam.Model
{

    /// <summary>
    ///  getSessionTokenInfo
    /// </summary>
    public class GetSessionTokenInfo
    {

        ///<summary>
        /// 操作保护验证方式：1-短信,2-邮箱,3-MFA
        ///Required:true
        ///</summary>
        [Required]
        public int Type{ get; set; }
        ///<summary>
        /// 验证码
        ///Required:true
        ///</summary>
        [Required]
        public string Code{ get; set; }
        ///<summary>
        /// 操作action
        ///Required:true
        ///</summary>
        [Required]
        public string BusinessAction{ get; set; }
        ///<summary>
        /// 令牌有效期，单位秒，OpenAPI第三方MFA方式验证有效，默认短信、邮箱token有效期300秒，MFA有效期30秒
        ///</summary>
        public int? DurationSeconds{ get; set; }
    }
}
