/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 京东云信用评分-OpenAPI接口
 * 京东云信用评分-OpenAPI接口
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using JDCloudSDK.Core.Auth;
using JDCloudSDK.Core.Client;
using JDCloudSDK.Core.Http;
using JDCloudSDK.Bri.Apis;
using JDCloudSDK.Bri.Model;
using System;
using System.Collections.Generic;
using System.Text;
#if NET40||NET35
#else
using System.Threading.Tasks;
#endif

namespace JDCloudSDK.Bri.Client
{
    /// <summary>
    ///  京东云信用评分-OpenAPI接口
    ///  京东云信用评分-OpenAPI接口
    ///  Bri Api 客户端
    ///</summary>
    public class BriClient : JdcloudClient
    {

        /// <summary>
        ///  默认私有构造函数
        /// </summary>
        private BriClient()
        {

        }

        /// <summary>
        /// 默认构造函数
        /// </summary>
        /// <param name="credentialsProvider">认证信息</param>
        /// <param name="httpRequestConfig">http 客户端配置信息</param>
        /// <param name="environment">sdk 环境配置信息</param>
        public BriClient(CredentialsProvider credentialsProvider, HttpRequestConfig httpRequestConfig,SDKEnvironment environment)
        {
            this.httpRequestConfig = httpRequestConfig;
            this.credentialsProvider = credentialsProvider;
            this.environment = environment;
        }

        /// <summary>
        /// 默认构造函数
        /// </summary>
        /// <param name="httpRequestConfig">http 客户端配置信息</param>
        /// <param name="credentialsProvider">认证信息</param>
        public BriClient(CredentialsProvider credentialsProvider,HttpRequestConfig httpRequestConfig)
        {
            this.httpRequestConfig = httpRequestConfig;
            this.credentialsProvider = credentialsProvider;
        }

        /// <summary>
        /// 默认构造函数，
        /// 注意如果使用此方法 httpRequestConfig 使用的http 请求 schema 为Https
        /// </summary>
        /// <param name="credentialsProvider">认证信息</param>
        public BriClient(CredentialsProvider credentialsProvider)
        {
            this.credentialsProvider = credentialsProvider;
        }

        /// <summary>
        ///  版本号 1.2.3
        ///</summary>
        public const string ClientVersion = "1.2.3";

        private const string apiVersion = "v1";
        private const string userAgentPrefix = "JdcloudSdkDotNet";
        private const string defaultEndpoint = "bri.jdcloud-api.com";
        private const string serviceName = "bri";
        private const string userAgent = userAgentPrefix + "/" + ClientVersion + " " + serviceName + "/" + apiVersion;


        private SDKEnvironment environment = new SDKEnvironment(defaultEndpoint);
        private CredentialsProvider credentialsProvider;
        private HttpRequestConfig httpRequestConfig;

        /// <summary>
        ///  获取证书信息
        ///</summary>
        public override CredentialsProvider CredentialsProvider   { get { return credentialsProvider; } }

        /// <summary>
        ///  获取http 客户端配置信息
        ///</summary>
        public override HttpRequestConfig HttpRequestConfig { get { return httpRequestConfig; } }

        /// <summary>
        ///  获取sdk环境配置信息
        ///</summary>
        public override SDKEnvironment SDKEnvironment { get { return environment; } }

        /// <summary>
        ///  获取用户自定义浏览器识别字符串
        ///</summary>
        public override string UserAgent { get { return userAgent; } }

        /// <summary>
        ///  获取服务名称
        ///</summary>
        public override string ServiceName { get { return serviceName; } }

        /// <summary>
        ///  获取版本号
        ///</summary>
        public override string Version { get { return apiVersion; } }



#if NET40||NET35
        /// <summary>
        ///  设置黑白名单
        /// </summary>
        /// <param name="request">请求参数信息</param>
        /// <returns>请求结果信息</returns>
        public SetBWListResponse SetBWList(SetBWListRequest request) {
            return  new SetBWListExecutor().Client(this).Execute<SetBWListResponse, SetBWListResult, SetBWListRequest>(request);
        }
#else
        /// <summary>
        ///  设置黑白名单
        /// </summary>
        /// <param name="request">请求参数信息</param>
        /// <returns>请求结果信息</returns>
        public async Task<SetBWListResponse> SetBWList(SetBWListRequest request) {
            return await new SetBWListExecutor().Client(this).Execute<SetBWListResponse, SetBWListResult, SetBWListRequest>(request).ConfigureAwait(false);
        }
#endif
#if NET40||NET35
        /// <summary>
        ///  获取数据信用评分
        /// </summary>
        /// <param name="request">请求参数信息</param>
        /// <returns>请求结果信息</returns>
        public CreditScoreResponse CreditScore(CreditScoreRequest request) {
            return  new CreditScoreExecutor().Client(this).Execute<CreditScoreResponse, CreditScoreResult, CreditScoreRequest>(request);
        }
#else
        /// <summary>
        ///  获取数据信用评分
        /// </summary>
        /// <param name="request">请求参数信息</param>
        /// <returns>请求结果信息</returns>
        public async Task<CreditScoreResponse> CreditScore(CreditScoreRequest request) {
            return await new CreditScoreExecutor().Client(this).Execute<CreditScoreResponse, CreditScoreResult, CreditScoreRequest>(request).ConfigureAwait(false);
        }
#endif
#if NET40||NET35
        /// <summary>
        ///  删除黑白名单
        /// </summary>
        /// <param name="request">请求参数信息</param>
        /// <returns>请求结果信息</returns>
        public DelBWListResponse DelBWList(DelBWListRequest request) {
            return  new DelBWListExecutor().Client(this).Execute<DelBWListResponse, DelBWListResult, DelBWListRequest>(request);
        }
#else
        /// <summary>
        ///  删除黑白名单
        /// </summary>
        /// <param name="request">请求参数信息</param>
        /// <returns>请求结果信息</returns>
        public async Task<DelBWListResponse> DelBWList(DelBWListRequest request) {
            return await new DelBWListExecutor().Client(this).Execute<DelBWListResponse, DelBWListResult, DelBWListRequest>(request).ConfigureAwait(false);
        }
#endif
#if NET40||NET35
        /// <summary>
        ///  获取黑白名单列表
        /// </summary>
        /// <param name="request">请求参数信息</param>
        /// <returns>请求结果信息</returns>
        public DescribeBWListResponse DescribeBWList(DescribeBWListRequest request) {
            return  new DescribeBWListExecutor().Client(this).Execute<DescribeBWListResponse, DescribeBWListResult, DescribeBWListRequest>(request);
        }
#else
        /// <summary>
        ///  获取黑白名单列表
        /// </summary>
        /// <param name="request">请求参数信息</param>
        /// <returns>请求结果信息</returns>
        public async Task<DescribeBWListResponse> DescribeBWList(DescribeBWListRequest request) {
            return await new DescribeBWListExecutor().Client(this).Execute<DescribeBWListResponse, DescribeBWListResult, DescribeBWListRequest>(request).ConfigureAwait(false);
        }
#endif

            /// <summary>
            ///  默认BriClient 构造器 接口
            ///</summary>
            public interface Builder
            {

                /// <summary>
                /// 设置认证信息参数
                /// </summary>
                /// <param name="provider">认证信息提供对象</param>
                /// <returns>briClient 构造器</returns>
                Builder CredentialsProvider(CredentialsProvider provider);

                /// <summary>
                /// 设置请求环境参数
                /// </summary>
                /// <param name="environment">环境参数信息</param>
                /// <returns>briClient 构造器</returns>
                Builder Environment(Core.Client.SDKEnvironment environment);

                /// <summary>
                /// http 请求配置信息
                /// </summary>
                /// <param name="config">http 请求配置信息</param>
                /// <returns>briClient 构造器</returns>
                Builder HttpRequestConfig(HttpRequestConfig config);

                /// <summary>
                ///  构造BriClient 对象
                ///</summary>
                BriClient Build();
            }

            /// <summary>
            ///  默认BriClient 构造器
            ///</summary>
            public class DefaultBuilder : Builder
            {
                /// <summary>
                ///  BriClient service client
                /// </summary>
                private  BriClient briClient;

                /// <summary>
                ///  默认BriClient 构造器构造对象
                ///</summary>
                public DefaultBuilder()
                {
                    briClient = new BriClient();
                }

                /// <summary>
                ///  构造BriClient 对象
                ///</summary>
                public BriClient Build()
                {
                    if (briClient.CredentialsProvider == null)
                    {
                        //if credentialsProvider not set, try load jdcloud global default  credentials provider
                        briClient.credentialsProvider = JdCloud.DefaultInstance.GetCredentialsProvider();
                        if (briClient.credentialsProvider == null)
                        {
                            throw new ArgumentNullException("BriClient build error: jdcloud credentials provider not set");
                        }
                    }
                    if (briClient.HttpRequestConfig == null)
                    {
                        briClient.httpRequestConfig = JdCloud.DefaultInstance.GetHttpRequestConfig();
                        if (briClient.httpRequestConfig == null)
                        {
                        throw new ArgumentNullException("BriClient build error: http request config not set");
                        }
                    }
                    return briClient;
                }

                /// <summary>
                /// 设置认证信息参数
                /// </summary>
                /// <param name="provider">认证信息提供对象</param>
                /// <returns>briClient 构造器</returns>
                public Builder CredentialsProvider(CredentialsProvider provider)
                {
                    briClient.credentialsProvider = provider;
                    return this;
                }

                /// <summary>
                /// 设置请求环境参数
                /// </summary>
                /// <param name="environment">环境参数信息</param>
                /// <returns>briClient 构造器</returns>
                public Builder Environment(SDKEnvironment environment)
                {
                    briClient.environment = environment;
                    return this;
                }

                /// <summary>
                /// http 请求配置信息
                /// </summary>
                /// <param name="config">http 请求配置信息</param>
                /// <returns>briClient 构造器</returns>
                public Builder HttpRequestConfig(HttpRequestConfig config)
                {
                    briClient.httpRequestConfig = config;
                    return this;
                }
            }
    }
}
