/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;

using JDCloudSDK.Core.Annotation;

namespace JDCloudSDK.Antipro.Model
{

    /// <summary>
    ///  createInstanceSpec
    /// </summary>
    public class CreateInstanceSpec
    {

        ///<summary>
        /// 防护包实例名称, 新购防护包时必传. 长度限制为 1-80 个字符, 只允许包含中文, 字母, 数字, -, ., /, _
        ///Required:true
        ///</summary>
        [Required]
        public string Name{ get; set; }
        ///<summary>
        /// 可防护 IP 数量, 1, 5, 10, 50, 100, 1000(不限)
        ///Required:true
        ///</summary>
        [Required]
        public int IpNum{ get; set; }
        ///<summary>
        /// 保底带宽: 10, 20, 30, 50, 单位: Gbps
        ///Required:true
        ///</summary>
        [Required]
        public int BpGbps{ get; set; }
        ///<summary>
        /// 弹性带宽: 0, 10, 20, 单位: Gbps
        ///Required:true
        ///</summary>
        [Required]
        public int EpGbps{ get; set; }
        ///<summary>
        /// 购买防护包时长, 新购防护包时必传. &lt;br&gt;- timeUnit 为 3 时, 可取值 1-9&lt;br&gt;- timeUnit 为 4 时, 可取值 1-3
        ///Required:true
        ///</summary>
        [Required]
        public int TimeSpan{ get; set; }
        ///<summary>
        /// 购买时长类型, 新购防护包时必传. &lt;br&gt;- 3: 月&lt;br&gt;- 4: 年
        ///Required:true
        ///</summary>
        [Required]
        public int TimeUnit{ get; set; }
    }
}
