/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Kafka.Model
{

    /// <summary>
    ///  instanceClass
    /// </summary>
    public class InstanceClass
    {

        ///<summary>
        /// 角色
        ///</summary>
        public string Role{ get; set; }
        ///<summary>
        /// 节点规格代码
        ///</summary>
        public string NodeClassCode{ get; set; }
        ///<summary>
        /// 节点cpu核数
        ///</summary>
        public int? NodeCpu{ get; set; }
        ///<summary>
        /// 节点内存单位GB
        ///</summary>
        public int? NodeMemoryGB{ get; set; }
        ///<summary>
        /// 节点个数
        ///</summary>
        public int? NodeCount{ get; set; }
        ///<summary>
        /// 磁盘类型
        ///</summary>
        public string NodeDiskType{ get; set; }
        ///<summary>
        /// 单节点磁盘大小单位GB
        ///</summary>
        public int? NodeDiskGB{ get; set; }
    }
}
