/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Smartdba.Model
{

    /// <summary>
    ///  slowDigestLog
    /// </summary>
    public class SlowDigestLog
    {

        ///<summary>
        /// 执行时间
        ///</summary>
        public Statistic ExecTime{ get; set; }
        ///<summary>
        /// 锁等待时间
        ///</summary>
        public Statistic LockTime{ get; set; }
        ///<summary>
        /// 返回行数
        ///</summary>
        public StatisticInt RowsSent{ get; set; }
        ///<summary>
        /// 扫描行数
        ///</summary>
        public StatisticInt RowsExamined{ get; set; }
        ///<summary>
        /// sql模板
        ///</summary>
        public string Sql{ get; set; }
        ///<summary>
        /// 数据库
        ///</summary>
        public string Database{ get; set; }
        ///<summary>
        /// 执行次数
        ///</summary>
        public int? QueryCount{ get; set; }
    }
}
