/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * JDCLOUD Renewal API v2
 * API related to Renewal
 *
 * OpenAPI spec version: v2
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using JDCloudSDK.Core.Auth;
using JDCloudSDK.Core.Client;
using JDCloudSDK.Core.Http;
using JDCloudSDK.Renewal.Apis;
using JDCloudSDK.Renewal.Model;
using System;
using System.Collections.Generic;
using System.Text;
#if NET40||NET35
#else
using System.Threading.Tasks;
#endif

namespace JDCloudSDK.Renewal.Client
{
    /// <summary>
    ///  JDCLOUD Renewal API v2
    ///  API related to Renewal
    ///  Renewal Api 客户端
    ///</summary>
    public class RenewalClient : JdcloudClient
    {

        /// <summary>
        ///  默认私有构造函数
        /// </summary>
        private RenewalClient()
        {

        }

        /// <summary>
        /// 默认构造函数
        /// </summary>
        /// <param name="credentialsProvider">认证信息</param>
        /// <param name="httpRequestConfig">http 客户端配置信息</param>
        /// <param name="environment">sdk 环境配置信息</param>
        public RenewalClient(CredentialsProvider credentialsProvider, HttpRequestConfig httpRequestConfig,SDKEnvironment environment)
        {
            this.httpRequestConfig = httpRequestConfig;
            this.credentialsProvider = credentialsProvider;
            this.environment = environment;
        }

        /// <summary>
        /// 默认构造函数
        /// </summary>
        /// <param name="httpRequestConfig">http 客户端配置信息</param>
        /// <param name="credentialsProvider">认证信息</param>
        public RenewalClient(CredentialsProvider credentialsProvider,HttpRequestConfig httpRequestConfig)
        {
            this.httpRequestConfig = httpRequestConfig;
            this.credentialsProvider = credentialsProvider;
        }

        /// <summary>
        /// 默认构造函数，
        /// 注意如果使用此方法 httpRequestConfig 使用的http 请求 schema 为Https
        /// </summary>
        /// <param name="credentialsProvider">认证信息</param>
        public RenewalClient(CredentialsProvider credentialsProvider)
        {
            this.credentialsProvider = credentialsProvider;
        }

        /// <summary>
        ///  版本号 1.1.0
        ///</summary>
        public const string ClientVersion = "1.1.0";

        private const string apiVersion = "v2";
        private const string userAgentPrefix = "JdcloudSdkDotNet";
        private const string defaultEndpoint = "renewal.jdcloud-api.com";
        private const string serviceName = "renewal";
        private const string userAgent = userAgentPrefix + "/" + ClientVersion + " " + serviceName + "/" + apiVersion;


        private SDKEnvironment environment = new SDKEnvironment(defaultEndpoint);
        private CredentialsProvider credentialsProvider;
        private HttpRequestConfig httpRequestConfig;

        /// <summary>
        ///  获取证书信息
        ///</summary>
        public override CredentialsProvider CredentialsProvider   { get { return credentialsProvider; } }

        /// <summary>
        ///  获取http 客户端配置信息
        ///</summary>
        public override HttpRequestConfig HttpRequestConfig { get { return httpRequestConfig; } }

        /// <summary>
        ///  获取sdk环境配置信息
        ///</summary>
        public override SDKEnvironment SDKEnvironment { get { return environment; } }

        /// <summary>
        ///  获取用户自定义浏览器识别字符串
        ///</summary>
        public override string UserAgent { get { return userAgent; } }

        /// <summary>
        ///  获取服务名称
        ///</summary>
        public override string ServiceName { get { return serviceName; } }

        /// <summary>
        ///  获取版本号
        ///</summary>
        public override string Version { get { return apiVersion; } }



#if NET40||NET35
        /// <summary>
        ///  开通、取消实例自动续费
        /// </summary>
        /// <param name="request">请求参数信息</param>
        /// <returns>请求结果信息</returns>
        public SetRenewalResponse SetRenewal(SetRenewalRequest request) {
            return  new SetRenewalExecutor().Client(this).Execute<SetRenewalResponse, SetRenewalResult, SetRenewalRequest>(request);
        }
#else
        /// <summary>
        ///  开通、取消实例自动续费
        /// </summary>
        /// <param name="request">请求参数信息</param>
        /// <returns>请求结果信息</returns>
        public async Task<SetRenewalResponse> SetRenewal(SetRenewalRequest request) {
            return await new SetRenewalExecutor().Client(this).Execute<SetRenewalResponse, SetRenewalResult, SetRenewalRequest>(request).ConfigureAwait(false);
        }
#endif
#if NET40||NET35
        /// <summary>
        ///  实例续费
        /// </summary>
        /// <param name="request">请求参数信息</param>
        /// <returns>请求结果信息</returns>
        public RenewInstanceResponse RenewInstance(RenewInstanceRequest request) {
            return  new RenewInstanceExecutor().Client(this).Execute<RenewInstanceResponse, RenewInstanceResult, RenewInstanceRequest>(request);
        }
#else
        /// <summary>
        ///  实例续费
        /// </summary>
        /// <param name="request">请求参数信息</param>
        /// <returns>请求结果信息</returns>
        public async Task<RenewInstanceResponse> RenewInstance(RenewInstanceRequest request) {
            return await new RenewInstanceExecutor().Client(this).Execute<RenewInstanceResponse, RenewInstanceResult, RenewInstanceRequest>(request).ConfigureAwait(false);
        }
#endif
#if NET40||NET35
        /// <summary>
        ///  查询可续费实例
        /// </summary>
        /// <param name="request">请求参数信息</param>
        /// <returns>请求结果信息</returns>
        public QueryInstanceResponse QueryInstance(QueryInstanceRequest request) {
            return  new QueryInstanceExecutor().Client(this).Execute<QueryInstanceResponse, QueryInstanceResult, QueryInstanceRequest>(request);
        }
#else
        /// <summary>
        ///  查询可续费实例
        /// </summary>
        /// <param name="request">请求参数信息</param>
        /// <returns>请求结果信息</returns>
        public async Task<QueryInstanceResponse> QueryInstance(QueryInstanceRequest request) {
            return await new QueryInstanceExecutor().Client(this).Execute<QueryInstanceResponse, QueryInstanceResult, QueryInstanceRequest>(request).ConfigureAwait(false);
        }
#endif

            /// <summary>
            ///  默认RenewalClient 构造器 接口
            ///</summary>
            public interface Builder
            {

                /// <summary>
                /// 设置认证信息参数
                /// </summary>
                /// <param name="provider">认证信息提供对象</param>
                /// <returns>renewalClient 构造器</returns>
                Builder CredentialsProvider(CredentialsProvider provider);

                /// <summary>
                /// 设置请求环境参数
                /// </summary>
                /// <param name="environment">环境参数信息</param>
                /// <returns>renewalClient 构造器</returns>
                Builder Environment(Core.Client.SDKEnvironment environment);

                /// <summary>
                /// http 请求配置信息
                /// </summary>
                /// <param name="config">http 请求配置信息</param>
                /// <returns>renewalClient 构造器</returns>
                Builder HttpRequestConfig(HttpRequestConfig config);

                /// <summary>
                ///  构造RenewalClient 对象
                ///</summary>
                RenewalClient Build();
            }

            /// <summary>
            ///  默认RenewalClient 构造器
            ///</summary>
            public class DefaultBuilder : Builder
            {
                /// <summary>
                ///  RenewalClient service client
                /// </summary>
                private  RenewalClient renewalClient;

                /// <summary>
                ///  默认RenewalClient 构造器构造对象
                ///</summary>
                public DefaultBuilder()
                {
                    renewalClient = new RenewalClient();
                }

                /// <summary>
                ///  构造RenewalClient 对象
                ///</summary>
                public RenewalClient Build()
                {
                    if (renewalClient.CredentialsProvider == null)
                    {
                        //if credentialsProvider not set, try load jdcloud global default  credentials provider
                        renewalClient.credentialsProvider = JdCloud.DefaultInstance.GetCredentialsProvider();
                        if (renewalClient.credentialsProvider == null)
                        {
                            throw new ArgumentNullException("RenewalClient build error: jdcloud credentials provider not set");
                        }
                    }
                    if (renewalClient.HttpRequestConfig == null)
                    {
                        renewalClient.httpRequestConfig = JdCloud.DefaultInstance.GetHttpRequestConfig();
                        if (renewalClient.httpRequestConfig == null)
                        {
                        throw new ArgumentNullException("RenewalClient build error: http request config not set");
                        }
                    }
                    return renewalClient;
                }

                /// <summary>
                /// 设置认证信息参数
                /// </summary>
                /// <param name="provider">认证信息提供对象</param>
                /// <returns>renewalClient 构造器</returns>
                public Builder CredentialsProvider(CredentialsProvider provider)
                {
                    renewalClient.credentialsProvider = provider;
                    return this;
                }

                /// <summary>
                /// 设置请求环境参数
                /// </summary>
                /// <param name="environment">环境参数信息</param>
                /// <returns>renewalClient 构造器</returns>
                public Builder Environment(SDKEnvironment environment)
                {
                    renewalClient.environment = environment;
                    return this;
                }

                /// <summary>
                /// http 请求配置信息
                /// </summary>
                /// <param name="config">http 请求配置信息</param>
                /// <returns>renewalClient 构造器</returns>
                public Builder HttpRequestConfig(HttpRequestConfig config)
                {
                    renewalClient.httpRequestConfig = config;
                    return this;
                }
            }
    }
}
