/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Distributed-Cloud-Physical-Server
 * 分布式云物理服务器操作相关的接口
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;
using JDCloudSDK.Core.Service;

using JDCloudSDK.Common.Model;
using JDCloudSDK.Core.Annotation;
using Newtonsoft.Json;

namespace  JDCloudSDK.Edcps.Apis
{

    /// <summary>
    ///  批量查询分布式云物理服务器详细信息&lt;br/&gt;
        ///         /// 支持分页查询，默认每页20条&lt;br/&gt;
        ///         /// 
    /// </summary>
    public class DescribeInstancesRequest : JdcloudRequest
    {
        ///<summary>
        /// 页码；默认为1
        ///</summary>
        public   int? PageNumber{ get; set; }
        ///<summary>
        /// 分页大小；默认为20；取值范围[20, 100]
        ///</summary>
        public   int? PageSize{ get; set; }
        ///<summary>
        /// 可用区，精确匹配
        ///</summary>
        public   string Az{ get; set; }
        ///<summary>
        /// 分布式云物理服务器名称，支持模糊匹配
        ///</summary>
        public   string Name{ get; set; }
        ///<summary>
        /// 网络类型，精确匹配，支持vpc
        ///</summary>
        public   string NetworkType{ get; set; }
        ///<summary>
        /// 实例类型，精确匹配，调用接口（describeDeviceTypes）获取实例类型
        ///</summary>
        public   string DeviceType{ get; set; }
        ///<summary>
        /// 子网ID
        ///</summary>
        public   string SubnetId{ get; set; }
        ///<summary>
        /// 是否启用外网, yes/no
        ///</summary>
        public   string EnableInternet{ get; set; }
        ///<summary>
        /// 主网口内网ip
        ///</summary>
        public   string PrivateIp{ get; set; }
        ///<summary>
        /// 辅网口内网ip
        ///</summary>
        public   string ExtensionPrivateIp{ get; set; }
        ///<summary>
        /// 密钥对id
        ///</summary>
        public   string KeypairId{ get; set; }
        ///<summary>
        /// 网口模式 单网口:bond,双网口:dual
        ///</summary>
        public   string InterfaceMode{ get; set; }
        ///<summary>
        /// instanceId - 分布式云物理服务器ID，精确匹配，支持多个&lt;br/&gt;
        /// status - 分布式云物理服务器状态，参考分布式云物理服务器状态，精确匹配，支持多个
        /// 
        ///</summary>
        public List<JDCloudSDK.Common.Model.Filter> Filters{ get; set; }

        ///<summary>
        /// 地域ID，可调用接口（describeEdCPSRegions）获取分布式云物理服务器支持的地域
        ///Required:true
        ///</summary>
        [Required]
        [JsonProperty("regionId")]
        public   string RegionIdValue{ get; set; }
    }
}