/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;

using Newtonsoft.Json;

namespace JDCloudSDK.Jdccs.Model
{

    /// <summary>
    ///  机房
    /// </summary>
    public class Idc
    {

        ///<summary>
        /// 机房英文标识
        ///</summary>
        [JsonProperty("idc")]
        public string IdcValue{ get; set; }
        ///<summary>
        /// 机房名称
        ///</summary>
        public string IdcName{ get; set; }
        ///<summary>
        /// 是否是商业化外部机房
        ///</summary>
        public bool IsExternalIdc{ get; set; }
        ///<summary>
        /// 机房地址
        ///</summary>
        public string Address{ get; set; }
        ///<summary>
        /// 机房主管
        ///</summary>
        public string Manager{ get; set; }
        ///<summary>
        /// 机房主管电话
        ///</summary>
        public string ManagerPhone{ get; set; }
        ///<summary>
        /// 机房类别 1:租用 2:自建 3:合作 4:其他
        ///</summary>
        public int? Category{ get; set; }
    }
}
