/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;

using JDCloudSDK.Core.Annotation;

namespace JDCloudSDK.Pod.Model
{

    /// <summary>
    ///  hg
    /// </summary>
    public class Hg
    {

        ///<summary>
        /// 默认值： http；可选值 http, https
        ///</summary>
        public string Scheme{ get; set; }
        ///<summary>
        /// 连接到pod的host信息，默认使用pod_ip，满足hostname或者ipv4格式
        ///</summary>
        public string Host{ get; set; }
        ///<summary>
        /// 范围：[1-65535]
        ///Required:true
        ///</summary>
        [Required]
        public int Port{ get; set; }
        ///<summary>
        /// HTTP的路径。范围：[1-256]
        ///Required:true
        ///</summary>
        [Required]
        public string Path{ get; set; }
        ///<summary>
        /// 对指定的端口和路径上的容器的 IP 地址执行 HTTP Get 请求。&lt;br&gt;
        /// 如果响应的状态码大于等于200 且小于 400，则诊断被认为是成功的。 
        ///</summary>
        public List<Hh> HttpHeader{ get; set; }
    }
}
