/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 云物理主机
 * 与云物理主机操作相关的接口
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;
using JDCloudSDK.Core.Service;

using JDCloudSDK.Common.Model;
using JDCloudSDK.Core.Annotation;

namespace  JDCloudSDK.Cps.Apis
{

    /// <summary>
    /// 查询云物理主机列表
    /// </summary>
    public class DescribeInstancesRequest : JdcloudRequest
    {
        ///<summary>
        ///页码；默认为1
        ///</summary>
        public   int? PageNumber{ get; set; }
        ///<summary>
        ///分页大小；默认为20；取值范围[10, 100]
        ///</summary>
        public   int? PageSize{ get; set; }
        ///<summary>
        ///可用区
        ///</summary>
        public   string Az{ get; set; }
        ///<summary>
        ///网络类型
        ///</summary>
        public   string NetworkType{ get; set; }
        ///<summary>
        ///设备类型
        ///</summary>
        public   string DeviceType{ get; set; }
        ///<summary>
        ///主机状态
        ///</summary>
        public   string Status{ get; set; }
        ///<summary>
        ///instanceId - 云物理主机ID，精确匹配，支持多个
        ///
        ///</summary>
        public List<Filter> Filters{ get; set; }

        ///<summary>
        ///Region ID
        ///Required:true
        ///</summary>
        [Required]
        public override  string RegionId{ get; set; }
    }
}