/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Cms.Model
{

    /// <summary>
    /// content
    /// </summary>
    public class Content
    {

        ///<summary>
        ///id
        ///</summary>
        public double? Id{ get; set; }
        ///<summary>
        ///栏目ID
        ///</summary>
        public double? CatalogId{ get; set; }
        ///<summary>
        ///标题
        ///</summary>
        public string Title{ get; set; }
        ///<summary>
        ///短标题
        ///</summary>
        public string ShortTitle{ get; set; }
        ///<summary>
        ///编辑人员
        ///</summary>
        public string Editor{ get; set; }
        ///<summary>
        ///审核人员
        ///</summary>
        public string Reviewer{ get; set; }
        ///<summary>
        ///锚点（文章二级标题）
        ///</summary>
        public string Subhead{ get; set; }
        ///<summary>
        ///锚点的代码
        ///</summary>
        public string SubheadId{ get; set; }
        ///<summary>
        ///描述
        ///</summary>
        public string Description{ get; set; }
        ///<summary>
        ///关键字
        ///</summary>
        public string Keywords{ get; set; }
        ///<summary>
        ///页面标题
        ///</summary>
        public string HeadTitle{ get; set; }
        ///<summary>
        ///状态(0:草稿;1:审核中;2:审核通过;3:回收站；)
        ///</summary>
        public int? Status{ get; set; }
        ///<summary>
        ///排序值
        ///</summary>
        public int? Sort{ get; set; }
        ///<summary>
        ///模板
        ///</summary>
        public string Templet{ get; set; }
        ///<summary>
        ///静态文件名
        ///</summary>
        public string Staticfilename{ get; set; }
        ///<summary>
        ///txt
        ///</summary>
        public string Txt{ get; set; }
        ///<summary>
        ///releaseTime
        ///</summary>
        public string ReleaseTime{ get; set; }
        ///<summary>
        ///createTime
        ///</summary>
        public string CreateTime{ get; set; }
        ///<summary>
        ///modifyTime
        ///</summary>
        public string ModifyTime{ get; set; }
        ///<summary>
        ///jssdrafturl
        ///</summary>
        public string Jssdrafturl{ get; set; }
        ///<summary>
        ///jsstxturl
        ///</summary>
        public string Jsstxturl{ get; set; }
        ///<summary>
        ///父级
        ///</summary>
        public double? ParentId{ get; set; }
        ///<summary>
        ///是否有文章
        ///</summary>
        public int? IsHasContent{ get; set; }
        ///<summary>
        ///级别
        ///</summary>
        public int? Level{ get; set; }
        ///<summary>
        ///chlidList
        ///</summary>
        public List<Content> ChlidList{ get; set; }
    }
}
