/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Cms.Model
{

    /// <summary>
    /// operation
    /// </summary>
    public class Operation
    {

        ///<summary>
        ///id
        ///</summary>
        public double? Id{ get; set; }
        ///<summary>
        ///名称
        ///</summary>
        public string Name{ get; set; }
        ///<summary>
        ///描述
        ///</summary>
        public string Description{ get; set; }
        ///<summary>
        ///图片地址
        ///</summary>
        public string PicUrl{ get; set; }
        ///<summary>
        ///icon类
        ///</summary>
        public string IconClass{ get; set; }
        ///<summary>
        ///链接地址
        ///</summary>
        public string LinkUrl{ get; set; }
        ///<summary>
        ///排序
        ///</summary>
        public int? Sort{ get; set; }
        ///<summary>
        ///0 底部运营位，1 运营位
        ///</summary>
        public int? Position{ get; set; }
        ///<summary>
        ///操作者
        ///</summary>
        public string Operator{ get; set; }
        ///<summary>
        ///createTime
        ///</summary>
        public double? CreateTime{ get; set; }
        ///<summary>
        ///updateTime
        ///</summary>
        public double? UpdateTime{ get; set; }
        ///<summary>
        ///content
        ///</summary>
        public string Content{ get; set; }
        ///<summary>
        ///存储文本内容的key
        ///</summary>
        public string ContentKey{ get; set; }
        ///<summary>
        ///jss保存文本的地址
        ///</summary>
        public string ContentUrl{ get; set; }
        ///<summary>
        ///banner编辑的类型
        ///</summary>
        public int? OperationType{ get; set; }
        ///<summary>
        ///运营位埋点
        ///</summary>
        public string Clstag{ get; set; }
        ///<summary>
        ///运营位标签
        ///</summary>
        public string Label{ get; set; }
    }
}
