/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Cms.Model
{

    /// <summary>
    /// product
    /// </summary>
    public class Product
    {

        ///<summary>
        ///id
        ///</summary>
        public double? Id{ get; set; }
        ///<summary>
        ///产品id
        ///</summary>
        public double? NavigationId{ get; set; }
        ///<summary>
        ///静态文件页
        ///</summary>
        public string NavigationName{ get; set; }
        ///<summary>
        ///navigationParentId
        ///</summary>
        public double? NavigationParentId{ get; set; }
        ///<summary>
        ///navigationParentName
        ///</summary>
        public string NavigationParentName{ get; set; }
        ///<summary>
        ///staticfilename
        ///</summary>
        public string Staticfilename{ get; set; }
        ///<summary>
        ///banner名称
        ///</summary>
        public string BannerName{ get; set; }
        ///<summary>
        ///banner模块的描述
        ///</summary>
        public string BannerDesc{ get; set; }
        ///<summary>
        ///banner上传图片地址
        ///</summary>
        public string ImageUrl{ get; set; }
        ///<summary>
        ///标签
        ///</summary>
        public string Label{ get; set; }
        ///<summary>
        ///标签是否显示
        ///</summary>
        public int? LabelStatus{ get; set; }
        ///<summary>
        ///说明
        ///</summary>
        public string Instruction{ get; set; }
        ///<summary>
        ///说明是否显示
        ///</summary>
        public string InstructionStatus{ get; set; }
        ///<summary>
        ///advantage
        ///</summary>
        public string Advantage{ get; set; }
        ///<summary>
        ///JSS存储产品优势的key
        ///</summary>
        public string AdvantageKey{ get; set; }
        ///<summary>
        ///JSS存储产品优势的url
        ///</summary>
        public string AdvantageUrl{ get; set; }
        ///<summary>
        ///fundesc
        ///</summary>
        public string Fundesc{ get; set; }
        ///<summary>
        ///JSS存储功能描述的key
        ///</summary>
        public string FundescKey{ get; set; }
        ///<summary>
        ///JSS存储产品功能的url
        ///</summary>
        public string FundescUrl{ get; set; }
        ///<summary>
        ///运营位的url
        ///</summary>
        public string OpraUrl{ get; set; }
        ///<summary>
        ///运营位链接
        ///</summary>
        public string OpraWebUrl{ get; set; }
        ///<summary>
        ///运营位是否显示
        ///</summary>
        public int? OpraStatus{ get; set; }
        ///<summary>
        ///应用场景状态值
        ///</summary>
        public int? ScenariosStatus{ get; set; }
        ///<summary>
        ///客户案例状态值
        ///</summary>
        public int? CustomerStatus{ get; set; }
        ///<summary>
        ///operator
        ///</summary>
        public string Operator{ get; set; }
        ///<summary>
        ///createTime
        ///</summary>
        public double? CreateTime{ get; set; }
        ///<summary>
        ///updateTime
        ///</summary>
        public double? UpdateTime{ get; set; }
        ///<summary>
        ///customerList
        ///</summary>
        public List<Customer> CustomerList{ get; set; }
        ///<summary>
        ///scenariosList
        ///</summary>
        public List<Scenarios> ScenariosList{ get; set; }
    }
}
