/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Zfs.Model
{

    /// <summary>
    ///  描述一个文件系统
    /// </summary>
    public class MountTarget
    {

        ///<summary>
        /// 文件系统ID
        ///</summary>
        public string FileSystemId{ get; set; }
        ///<summary>
        /// ipv4地址
        ///</summary>
        public string IpAddress{ get; set; }
        ///<summary>
        /// 挂载目标状态
        ///</summary>
        public string Status{ get; set; }
        ///<summary>
        /// 挂载目标ID
        ///</summary>
        public string MountTargetId{ get; set; }
        ///<summary>
        /// 子网ID
        ///</summary>
        public string SubnetId{ get; set; }
        ///<summary>
        /// vpcID
        ///</summary>
        public string VpcId{ get; set; }
        ///<summary>
        /// 创建时间
        ///</summary>
        public string CreateTime{ get; set; }
        ///<summary>
        /// dns名称
        ///</summary>
        public string DnsName{ get; set; }
    }
}
