/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;

using JDCloudSDK.Core.Annotation;

namespace JDCloudSDK.Renewal.Model
{

    /// <summary>
    ///  queryInstanceParam
    /// </summary>
    public class QueryInstanceParam
    {

        ///<summary>
        /// 业务线
        ///Required:true
        ///</summary>
        [Required]
        public string AppCode{ get; set; }
        ///<summary>
        /// 产品线
        ///Required:true
        ///</summary>
        [Required]
        public string ServiceCode{ get; set; }
        ///<summary>
        /// 资源名称
        ///</summary>
        public string InstanceName{ get; set; }
        ///<summary>
        /// 资源ID
        ///</summary>
        public string InstanceId{ get; set; }
        ///<summary>
        /// 资源续费状态(AUTO-开通自动续费资源,MANUAL-未开通自动续费资源,ALL-全部资源)
        ///</summary>
        public string RenewStatus{ get; set; }
        ///<summary>
        /// 资源计费类型(CONFIG-按配置,FLOW-按用量,MONTHLY-包年包月)，不传显示全部资源
        ///</summary>
        public string BillingType{ get; set; }
        ///<summary>
        /// 资源到期类型(EXPIRED-已到期,UNEXPIRED-未到期,ONE-1天内到期,THREE-3天内到期,SEVEN-7天内到期,ALL_TIME-全部)
        ///</summary>
        public string ExpireType{ get; set; }
        ///<summary>
        /// 主机绑定的内网IP地址
        ///</summary>
        public string IpAddress{ get; set; }
        ///<summary>
        /// 当前页码，不传默认为1
        ///</summary>
        public int? PageNumber{ get; set; }
        ///<summary>
        /// 每页条数，不传默认为10
        ///</summary>
        public int? PageSize{ get; set; }
    }
}
