/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Deploy.Model
{

    /// <summary>
    ///  deployStage
    /// </summary>
    public class DeployStage
    {

        ///<summary>
        /// code
        ///</summary>
        public int? StageCode{ get; set; }
        ///<summary>
        /// name
        ///</summary>
        public string StageName{ get; set; }
        ///<summary>
        /// 状态（0未执行，1执行，2失败）
        ///</summary>
        public int? StageStatus{ get; set; }
        ///<summary>
        /// 描述
        ///</summary>
        public string StageMessage{ get; set; }
        ///<summary>
        /// 部署完成的实例数
        ///</summary>
        public int? SucceedCount{ get; set; }
        ///<summary>
        /// 所有实例数
        ///</summary>
        public int? TotalCount{ get; set; }
        ///<summary>
        /// CreateTime
        ///</summary>
        public int? CreateTime{ get; set; }
        ///<summary>
        /// UpdateTime
        ///</summary>
        public int? UpdateTime{ get; set; }
    }
}
