/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 文本检测相关接口
 * API related to text scan
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Censor.Model
{

    /// <summary>
    ///  emotionAnalysisResult
    /// </summary>
    public class EmotionAnalysisResult
    {

        ///<summary>
        /// 本次请求数据标识，可以根据该标识查询数据最新结果
        ///</summary>
        public string TaskId{ get; set; }
        ///<summary>
        /// negative（负向情绪），neutral（中性情绪），positive（正向情绪），unknown（未知）
        ///</summary>
        public string Sentiment{ get; set; }
        ///<summary>
        /// 0~1，代表正向情绪倾向，分数越高，正向情绪越高
        ///</summary>
        public float? PositiveProb{ get; set; }
        ///<summary>
        /// 0~1，代表正向情绪倾向，分数越高，正向情绪越高
        ///</summary>
        public float? NegativeProb{ get; set; }
    }
}
