/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Jdro.Model
{

    /// <summary>
    ///  resourceChange
    /// </summary>
    public class ResourceChange
    {

        ///<summary>
        /// Action
        ///</summary>
        public string Action{ get; set; }
        ///<summary>
        /// 更新操作中将对资源做的改变详情
        ///</summary>
        public List<ResourceChangeDetail> Details{ get; set; }
        ///<summary>
        /// 资源在模板中的逻辑id
        ///</summary>
        public string LogicalResourceId{ get; set; }
        ///<summary>
        /// 资源物理id
        ///</summary>
        public string PhysicalResourceId{ get; set; }
        ///<summary>
        /// Replacement
        ///</summary>
        public string Replacement{ get; set; }
        ///<summary>
        /// 资源类型
        ///</summary>
        public string ResourceType{ get; set; }
        ///<summary>
        /// 更新操作中修改发生的位置
        ///</summary>
        public List<string> Scope{ get; set; }
    }
}
