/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Monitor.Model
{

    /// <summary>
    ///  oneClickAlarmOption
    /// </summary>
    public class OneClickAlarmOption
    {

        ///<summary>
        /// 通知的联系人
        /// in: body
        ///</summary>
        public List<BaseContact> Contacts{ get; set; }
        ///<summary>
        /// 资源维度(vm-gpu、mongos-shard)
        ///</summary>
        public string Dimension{ get; set; }
        ///<summary>
        /// 资源维度名称
        ///</summary>
        public string DimensionName{ get; set; }
        ///<summary>
        /// 是否启用, 1表示启用规则，0表示禁用规则
        ///</summary>
        public long? Enabled{ get; set; }
        ///<summary>
        /// 一键报警规则下的报警规则id
        ///</summary>
        public string PolicyId{ get; set; }
        ///<summary>
        /// 资源类型(vm、database、db_ro……)
        ///</summary>
        public string Product{ get; set; }
        ///<summary>
        /// 资源类型名称
        ///</summary>
        public string ProductName{ get; set; }
        ///<summary>
        /// RuleOption
        ///</summary>
        public RuleOptionDetail RuleOption{ get; set; }
    }
}
