/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Ipanti.Model
{

    /// <summary>
    ///  certInfo
    /// </summary>
    public class CertInfo
    {

        ///<summary>
        /// 通用名称
        ///</summary>
        public string Domain{ get; set; }
        ///<summary>
        /// 证书生效时间
        ///</summary>
        public string From{ get; set; }
        ///<summary>
        /// 证书到期时间
        ///</summary>
        public string To{ get; set; }
        ///<summary>
        /// 证书组织
        ///</summary>
        public string User{ get; set; }
        ///<summary>
        /// 加密算法
        ///</summary>
        public string SigAlgName{ get; set; }
        ///<summary>
        /// 颁发者
        ///</summary>
        public string Issuer{ get; set; }
    }
}
