/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Logs.Model
{

    /// <summary>
    ///  apiConfEnd
    /// </summary>
    public class ApiConfEnd
    {

        ///<summary>
        /// api name
        ///</summary>
        public string ApiName{ get; set; }
        ///<summary>
        /// apiType: 1-openapi,2-http
        ///</summary>
        public long? ApiType{ get; set; }
        ///<summary>
        /// 记录id
        ///</summary>
        public long? Id{ get; set; }
        ///<summary>
        /// method: GET/POST ...
        ///</summary>
        public string Method{ get; set; }
        ///<summary>
        /// params
        ///</summary>
        public List<Pair> Params{ get; set; }
        ///<summary>
        /// reps
        ///</summary>
        public List<Pair> Resp{ get; set; }
        ///<summary>
        /// serviceCode
        ///</summary>
        public string ServiceCode{ get; set; }
        ///<summary>
        /// url
        ///</summary>
        public string Url{ get; set; }
        ///<summary>
        /// version: v1
        ///</summary>
        public string Version{ get; set; }
    }
}
