/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Service Account
 * 用户服务管理
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;
using JDCloudSDK.Core.Service;


namespace  JDCloudSDK.Mps.Apis
{

    /// <summary>
    ///  用户查询服务状态
    /// </summary>
    public class QueryServiceStatusResult : JdcloudResult
    {
        ///<summary>
        /// 用户PIN
        ///</summary>
        public   string UserPin{ get; set; }
        ///<summary>
        /// 用户开通状态
        /// - UNOPENED 服务未开通
        /// - NORMAL 正常
        /// - ARREAR_STOPPED 欠费停服
        /// - ARREAR_DESTROYED 欠费删除
        /// - OVERDUE_STOPPED 过期停服
        /// - OVERDUE_DESTROYED 过期删除
        /// - USER_DESTROYED 用户删除
        /// - ADMIN_DESTROYED 管理员删除
        /// 
        ///</summary>
        public   string Status{ get; set; }
    }
}