/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * LogSearch APIs
 * 日志搜索接口
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;
using JDCloudSDK.Core.Service;

using JDCloudSDK.Logs.Model;
using JDCloudSDK.Core.Annotation;
using Newtonsoft.Json;

namespace  JDCloudSDK.Logs.Apis
{

    /// <summary>
    ///  搜索日志上下文
    /// </summary>
    public class SearchLogContextRequest : JdcloudRequest
    {
        ///<summary>
        /// 查询anchor,基于该值偏移进行上下文检索
        ///Required:true
        ///</summary>
        [Required]
        public List<object> Anchor{ get; set; }

        ///<summary>
        /// 搜索方向,默认both,可取值:up,down,both
        ///</summary>
        public   string Direction{ get; set; }
        ///<summary>
        /// 指定返回字段，只对系统日志生效，不填默认按照产品线配置返回字段，Name支持：key，Values填入返回字段
        ///</summary>
        public List<Filter> Filters{ get; set; }

        ///<summary>
        /// 日志记录ID
        ///Required:true
        ///</summary>
        [Required]
        public   string Id{ get; set; }
        ///<summary>
        /// 查看上下文行数大小，最大支持200
        ///Required:true
        ///</summary>
        [Required]
        public   long LineSize{ get; set; }
        ///<summary>
        /// 查询日志时返回的时间戳
        ///Required:true
        ///</summary>
        [Required]
        public   long Time{ get; set; }
        ///<summary>
        /// 地域 Id
        ///Required:true
        ///</summary>
        [Required]
        [JsonProperty("regionId")]
        public   string RegionIdValue{ get; set; }
        ///<summary>
        /// 日志集 UID
        ///Required:true
        ///</summary>
        [Required]
        public   string LogsetUID{ get; set; }
        ///<summary>
        /// 日志主题 UID
        ///Required:true
        ///</summary>
        [Required]
        public   string LogtopicUID{ get; set; }
    }
}