/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;


namespace JDCloudSDK.Function.Model
{

    /// <summary>
    ///  functionSpec
    /// </summary>
    public class FunctionSpec
    {

        ///<summary>
        /// 函数Id
        ///</summary>
        public string FunctionId{ get; set; }
        ///<summary>
        /// 函数名称
        ///</summary>
        public string Name{ get; set; }
        ///<summary>
        /// 函数描述
        ///</summary>
        public string Description{ get; set; }
        ///<summary>
        /// 函数运行环境，目前有python3
        ///</summary>
        public string Runtime{ get; set; }
        ///<summary>
        /// 函数创建时间
        ///</summary>
        public string CreateTime{ get; set; }
        ///<summary>
        /// 函数最后更新时间
        ///</summary>
        public string UpdateTime{ get; set; }
        ///<summary>
        /// 函数版本名称
        ///</summary>
        public string Version{ get; set; }
        ///<summary>
        /// 代码包下载的url地址
        ///</summary>
        public string DownloadUrl{ get; set; }
    }
}
