/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;

using JDCloudSDK.Core.Annotation;

namespace JDCloudSDK.Userpool.Model
{

    /// <summary>
    ///  poolUser
    /// </summary>
    public class PoolUser
    {

        ///<summary>
        /// 用户名：4-30位，字母、数字、汉字、-、_(不能是纯数字)
        ///Required:true
        ///</summary>
        [Required]
        public string UserName{ get; set; }
        ///<summary>
        /// 字母或数字
        ///</summary>
        public string PoolUid{ get; set; }
        ///<summary>
        /// 昵称：1-100位，任意字符
        ///</summary>
        public string NickName{ get; set; }
        ///<summary>
        /// 用户姓名：1-100位，任意字符
        ///</summary>
        public string Name{ get; set; }
        ///<summary>
        /// 用户资料
        ///</summary>
        public string Profile{ get; set; }
        ///<summary>
        /// 长度为4-20位，包含数字、大写字母、小写字母、ASCII符号（不包括空格）中的一种即可
        ///Required:true
        ///</summary>
        [Required]
        public string Password{ get; set; }
        ///<summary>
        /// 手机号码，一期仅支持中国大陆手机格式
        ///</summary>
        public string Mobile{ get; set; }
        ///<summary>
        /// 用户角色：1-100位，任意字符
        ///</summary>
        public string CustomRole{ get; set; }
        ///<summary>
        /// 用户创建时间
        ///</summary>
        public DateTime? CreateTime{ get; set; }
        ///<summary>
        /// 用户更新时间
        ///</summary>
        public DateTime? UpdateTime{ get; set; }
    }
}
