/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;

using JDCloudSDK.Core.Annotation;

namespace JDCloudSDK.Apigateway.Model
{

    /// <summary>
    ///  API分组
    /// </summary>
    public class BindJdsfGroup
    {

        ///<summary>
        /// 微服务网关名称
        ///</summary>
        public string JdsfName{ get; set; }
        ///<summary>
        /// 微服务注册中心ID
        ///</summary>
        public string JdsfRegistryName{ get; set; }
        ///<summary>
        /// 环境信息
        ///Required:true
        ///</summary>
        [Required]
        public string Environment{ get; set; }
        ///<summary>
        /// 微服务网关ID
        ///Required:true
        ///</summary>
        [Required]
        public string JdsfId{ get; set; }
        ///<summary>
        /// VPC类型时，传vpc对应的IP:port
        ///</summary>
        public string JdsfParam{ get; set; }
        ///<summary>
        /// 微服务网关region ID
        ///</summary>
        public string JdsfRegion{ get; set; }
        ///<summary>
        /// 分组类型：api_group（api分组）、jdsf_group（微服务分组）默认api_group
        ///</summary>
        public string GroupType{ get; set; }
    }
}
