/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Redis SpecConfig API
 * 缓存Redis实例规格配置接口
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */


using System;
using System.Collections.Generic;
using System.Text;
using JDCloudSDK.Core.Service;

using JDCloudSDK.Redis.Model;

namespace  JDCloudSDK.Redis.Apis
{

    /// <summary>
    ///  查询缓存Redis实例的规格配置信息
    /// </summary>
    public class DescribeSpecConfigResult : JdcloudResult
    {
        ///<summary>
        /// 单分片规格，自定义分片规格实例才有
        ///</summary>
        public   ShardSpec ShardSpec{ get; set; }
        ///<summary>
        /// 实例规格
        ///</summary>
        public   InstanceSpec InstanceSpec{ get; set; }
    }
}